### PR TITLE
Intra-station Margins Functionality

### PR DESCRIPTION
**Pull request by awhipp**
I've been looking for something to quickly look up margins within stations, and found your app as a good base. So I figured I would share what I did and leave it up to you if you want the functionality in your application.

### CODE REVIEW

**Comment by w9jds** [comment]
Cool, I'm in the middle of rewriting all the views and loaders, so I will add this in when I get back to fulling working.

What is the biggest the list of margins will come back? If it is less than 1k, Hashmap is probably overkill.

**Comment by awhipp** [comment]
The largest list will be equal to the region with the most number of stations (so I imagine it is less than 1k). This is because it takes the highest buy order, and the lowest sell order for each station in the region. A margin is determined when there is both a buy and sell order for a station. If there is just one then a margin cannot be computed and it is dropped. It was something quick I threw together a couple hours so feel free to modify it as you see fit

**Comment by w9jds** [comment]
Sounds good. Thanks!

**Comment by w9jds** [comment]
How does this look? [Margins Example](https://drive.google.com/file/d/0B8RN58CDarIOLU9KQTdpTTd5a3M/view?usp=sharing)

**Comment by awhipp** [comment]
Looks perfect to me. Just figured it would be a nice addition since not many apps do that calculation for you and I know a lot of people would enjoy it if they station trade.

**Comment by w9jds** [comment]
Sounds good. It will be coming with the next update which will include Market History, Station Margins, Completely new backend, Last region selected being stored, and orders all loaded with one network call :smile:

**Pull request merged**
